////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
/////////////                                                    ///////////////
/////////////                                                    ///////////////
/////////////  Manuel Moya Ferrer --- Jose Manuel García Giménez ///////////////
/////////////                                                    ///////////////
/////////////          Práctica 8 -- COMECOCOS                   ///////////////   
/////////////                                                    ///////////////
/////////////          3ºTelecomunicaciones UGR                  ///////////////
/////////////         Especialidad en Telemática                 ///////////////
/////////////                                                    ///////////////
/////////////                                                    ///////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////




package guiComecocos;

import data.*;
import static data.Rejilla.BLOQUE;
import static data.Rejilla.BloqueSalida;
import static data.Rejilla.PuntoGrande;
import static data.Rejilla.PuntoPequeño;
import static data.Rejilla.VACIO;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
 

import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 * Ventana principal que contiene el menú e incluye a RejillaPanel, la cual es 
 * la ventana donde se ve el juego.
 * @author manuel
 */
public class ComecocosFrame extends javax.swing.JFrame {

        private Rejilla rejilla;
        public static Mueve mueve;
        
        
        
    /**
     * Constructor Frame Comecocos
     */
    public ComecocosFrame() {
        initComponents();
        rejilla=new Rejilla(28,31);  //28 31
        mueve=new Mueve(this, 7);   //5 es el nivel
        mueve.reanudar();

    }
    
    /**
     * Inicia el juego y sirve para reiniciarlo posteriormente,
     * colocando el mapa con los puntos y los fantasmas
     * en sus posisicones iniciales.
     * 
     * @throws InterruptedException 
     */
    public void inicializaJuego() throws InterruptedException{
            mueve.reanudar();
            rejilla.initStringRejilla();
            
            rejillaPanel1.reiniciarPuntos();
            rejillaPanel1.comecocos.reiniciar(1, 1);
            rejillaPanel1.fantasma[0].reiniciar(12, 15);
            rejillaPanel1.fantasma[1].reiniciar(13, 15);
            rejillaPanel1.fantasma[2].reiniciar(14, 15);
            rejillaPanel1.fantasma[3].reiniciar(15, 15);
         
    }
    
       
    
    /**
     * Devuelve rejillaPanel1
     * @return RejillaPanel
     */
    
    public RejillaPanel getPanel(){
        return rejillaPanel1;
    }
    
    /**
     * Devuelve el mapa Rejilla.
     * @return  rejilla
     */
    public Rejilla getRejilla(){
        return rejilla;
    }
       
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rejillaPanel1 = new RejillaPanel(this);
        jLabel1 = new javax.swing.JLabel();
        jTextoPuntuacion = new javax.swing.JTextField();
        BotonReanudar = new javax.swing.JButton();
        BotonPausa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextoVidas = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        NewItem = new javax.swing.JMenuItem();
        ExitItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        rejillaPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ComecocosFrame.this.mouseEntered(evt);
            }
        });
        rejillaPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ComecocosFrame.this.keyPressed(evt);
            }
        });

        javax.swing.GroupLayout rejillaPanel1Layout = new javax.swing.GroupLayout(rejillaPanel1);
        rejillaPanel1.setLayout(rejillaPanel1Layout);
        rejillaPanel1Layout.setHorizontalGroup(
            rejillaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        rejillaPanel1Layout.setVerticalGroup(
            rejillaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Meera", 1, 24)); // NOI18N
        jLabel1.setText("Vidas: ");

        jTextoPuntuacion.setFont(new java.awt.Font("Meera", 1, 36)); // NOI18N
        jTextoPuntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoPuntuacionActionPerformed(evt);
            }
        });

        BotonReanudar.setText("Reanudar");
        BotonReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReanudarActionPerformed(evt);
            }
        });

        BotonPausa.setText("Pausa");
        BotonPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPausaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Meera", 1, 24)); // NOI18N
        jLabel2.setText("Puntos: ");

        jTextoVidas.setFont(new java.awt.Font("Meera", 1, 36)); // NOI18N
        jTextoVidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoVidasActionPerformed(evt);
            }
        });

        FileMenu.setMnemonic('F');
        FileMenu.setText("File");

        NewItem.setMnemonic('N');
        NewItem.setText("New");
        NewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewItemActionPerformed(evt);
            }
        });
        FileMenu.add(NewItem);

        ExitItem.setMnemonic('X');
        ExitItem.setText("Exit");
        ExitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitItemActionPerformed(evt);
            }
        });
        FileMenu.add(ExitItem);

        jMenuBar1.add(FileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rejillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextoPuntuacion, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jTextoVidas))
                        .addGap(9, 9, 9))
                    .addComponent(BotonPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonReanudar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(rejillaPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextoPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextoVidas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonPausa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonReanudar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewItemActionPerformed
            try {
                inicializaJuego();
            } catch (InterruptedException ex) {
                Logger.getLogger(ComecocosFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
    
            
                 
    }//GEN-LAST:event_NewItemActionPerformed

    private void ExitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitItemActionPerformed
            System.exit(0);        
    }//GEN-LAST:event_ExitItemActionPerformed

    private void keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyPressed

    private void mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_mouseEntered

    private void jTextoPuntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoPuntuacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextoPuntuacionActionPerformed

    private void BotonReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReanudarActionPerformed
        mueve.reanudar();
        
    }//GEN-LAST:event_BotonReanudarActionPerformed

    private void BotonPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPausaActionPerformed
        mueve.suspender();
    }//GEN-LAST:event_BotonPausaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened

    private void jTextoVidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoVidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextoVidasActionPerformed

   
    /**
     * Método para añadir puntos a la puntuación actual
     *
     * @param puntos 
     */
    public void añadirPuntos(int puntos){
        jTextoPuntuacion.setText(Integer.toString(puntos)); 
    }
    
    /**
     * Método que recibe un número de vidas y lo escribe en el textfiel de vidas.
     * @param vidas 
     */
    public void EstablecerVidasEnTextArea(int vidas) {
        jTextoVidas.setText(Integer.toString(vidas));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComecocosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComecocosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPausa;
    private javax.swing.JButton BotonReanudar;
    private javax.swing.JMenuItem ExitItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem NewItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextoPuntuacion;
    private javax.swing.JTextField jTextoVidas;
    private guiComecocos.RejillaPanel rejillaPanel1;
    // End of variables declaration//GEN-END:variables

    
}
